#!/bin/sh

if [ $# != 2 ]; then
    echo "Usage: $0 <master_ip> <authzcode> "
    exit 1
fi

MASTERIP=$1
AUTHZCODE=$2

#pre init check env var
#-------------------------------------
if [ -z "${XDPREFIX}" ]
then
    echo "XDPREFIX is not init"
    exit 1
fi

#1. init user(xdagent) enviroment 
#===============================
rm -rf ${XDPREFIX}/home/xdagent
userdel xdagent
useradd xdagent -g named -s /sbin/nologin -d ${XDPREFIX}/home/xdagent
mkdir -p ${XDPREFIX}/home/xdagent/{.ssh,prog,iplatency}
touch ${XDPREFIX}/home/xdagent/.ssh/known_hosts
ssh-keygen -t dsa -f ${XDPREFIX}/home/xdagent/rsync-key -N ""


#2. register to Master 
#================================
echo "xdreg agent -m $MASTERIP -a $AUTHZCODE"
${XDPREFIX}/bin/xdreg agent -m $MASTERIP -a $AUTHZCODE
if [ $? -ne 0 ]; then
exit 1
fi


#3. sync program and configuration
#=============================== 
mv ~/.ssh/known_hosts ~/.ssh/known_hosts.bak
cp ${XDPREFIX}/home/xdagent/.ssh/known_hosts ~/.ssh/known_hosts
rsync -avz -e "ssh -i ${XDPREFIX}/home/xdagent/rsync-key" xbaydns@$MASTERIP:${XDPREFIX}/home/xbaydns/agent/prog ${XDPREFIX}/home/xdagent
rsync -avz -e "ssh -i ${XDPREFIX}/home/xdagent/rsync-key" xbaydns@$MASTERIP:${XDPREFIX}/home/xbaydns/agent/agent.conf ${XDPREFIX}/home/xdagent
mv ~/.ssh/known_hosts.bak ~/.ssh/known_hosts


#4. setup up cron
#==================================
echo "*/5 * * * * ${XDPREFIX}/home/xdagent/prog/UpdateAgent.sh">${XDPREFIX}/home/xdagent/prog/crontab
echo "*/5 * * * * ${XDPREFIX}/home/xdagent/prog/UpdateIPList.sh">>${XDPREFIX}/home/xdagent/prog/crontab
echo "*/5 * * * * ${XDPREFIX}/home/xdagent/prog/ProbeIPlist.sh">>${XDPREFIX}/home/xdagent/prog/crontab
echo "*/5 * * * * ${XDPREFIX}/home/xdagent/prog/UploadProbeResults.sh">>${XDPREFIX}/home/xdagent/prog/crontab
crontab -u xdagent -l >${XDPREFIX}/home/xdagent/old_crontab 2>/dev/null
crontab -u xdagent ${XDPREFIX}/home/xdagent/prog/crontab


chmod +x ${XDPREFIX}/home/xdagent/prog/*
chown -R xdagent:named ${XDPREFIX}/home/xdagent
chmod 700 ${XDPREFIX}/home/xdagent



#5. message
#=============================
MYNAME=`cat ${XDPREFIX}/home/xdagent/myname`
echo "\



XBayDNS(enabled agent) installed successfully!
MASTER    :$MASTERIP
AGENT CODE:$MYNAME
HOME      :${XDPREFIX}/home/xdagent

"
