#!/bin/sh

if [ $# != 3 ]; then
    echo "Usage: $0 <master_ip> <path_to_bind_chroot> <slave_name>"
    exit 1
fi

MASTERIP=$1
BINDCHROOT=$2
SLAVE_NAME=$3


#1.init sync&cron enviroment 
#===========================
rm -rf /home/xdslave
userdel xdslave
groupdel xdslave
groupadd xdslave
useradd xdslave -g xdslave -s /sbin/nologin -d /home/xdslave
mkdir -p /home/xdslave/prog
mkdir -p /home/xdslave/named/{log,etc/{acl,view,dynamic}}

ssh-keygen -t dsa -f /home/xslave/rsync-key -N ""

xdreg slave -m $MASTER -s $SLAVE_NAME
if [ $? -ne 0 ]; then
exit 1
fi

rsync -avz -e 'ssh -i /home/xdslave/rsync-key' xdagent@$MASTERIP:/home/xdslave/prog /home/xdagent
rsync -avz -e 'ssh -i /home/xdslave/rsync-key' xdagent@$MASTERIP:/home/xdslave/slave.conf /home/xdagent/slave.conf

chown -R xdslave:xdslave /home/xdslave
chmod 700 /home/xdslave

/home/xdslave/prog/InstallCrontab.sh

#2.prepare bind's chroot
#-----------------------
mkdir -p $BINDCHROOT/{etc,dev,var/{run,dump,stats,log}}
chown -R named:named $BINDCHROOT/var/{run,dump,stats}
touch $BINDCHROOT/var/log/named.log
chown -R named:named $BINDCHROOT/var/log/named.log

rm $BINDCHROOT/dev/{random,zero,null}
mknod $BINDCHROOT/dev/random c 1 8
mknod $BINDCHROOT/dev/zero c 1 5
mknod $BINDCHROOT/dev/null c 1 3

#3.set envionment variables
#==========================
echo "\
XBAYDNS_CHROOT_PATH=$BINDCHROOT
XBAYDNS_BIND_CONF=/etc
XBAYDNS_BIND_START=/usr/local/sbin/named
XBAYDNS_BIND_USER=named
export PATH XBAYDNS_CHROOT_PATH XBAYDNS_BIND_CONF XBAYDNS_BIND_START XBAYDNS_BIND_USER
"|tee /home/xdslave/xdenv

chmod +x /home/xdslave/xdenv
source /home/xdslave/xdenv
xdinitbind slave $MASTERIP

echo "\



----------------------------- Welcome to XBayDNS ---------------------------

