#!/bin/sh

#pre init check env var
#-------------------------------------
if [ -z "${XDPREFIX}" ]
then
    echo "XDPREFIX is not init"
    exit 1
fi

xbaydns_path=`${XDPREFIX}/bin/xdwherepkg`/xbaydnsweb
echo $xbaydns_path
cd $xbaydns_path
source ${XDPREFIX}/home/xbaydns/xdenv
${XDPREFIX}/bin/python2.5 manage.py runserver 0.0.0.0:80
