#!/bin/sh

#pre init check env var
#-------------------------------------
if [ -z "${XDPREFIX}" ]
then
    echo "XDPREFIX is not init"
    exit 1
fi

xbaydns_path=`${XDPREFIX}/bin/python2.5 ${XDPREFIX}/bin/xdwherepkg`/xbaydnsweb
cd $xbaydns_path
${XDPREFIX}/bin/python2.5 manage.py runserver 0.0.0.0:8080
